apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/nginx-download
  - ../base/gethomepage
  - ../base/diskube
  - ../base/glance
  - ../base/haste-server
  - ../base/killedby
#  - ../base/k8s-dashboard
  - ../base/weave-gitops
  - ../base/kube-prometheus-stack